services:
  
  devcontainer: 
    build: 
      context: .
    privileged: true
    network_mode: "host"
    volumes:
      - /home/jeanine/.ssh:/home/jeanine/.ssh
      # - $(readlink -f $SSH_AUTH_SOCK):/ssh-agent
      - /home/jeanine/dev/Lowpad.Robot:/home/jeanine/dev/Lowpad.Robot
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /etc/udev/rules.d:/etc/udev/rules.d
      - /lib/udev/rules.d:/lib/udev/rules.d
    devices: 
      - /dev:/dev
    container_name: rosdevcontainer
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    command: sleep infinity

